Support Jakarta EE Namespace
MicroShed/microshed-testing pull request #312
Opened 2023-11-08 17:27 UTC by KyleAure

Fixes #292

2023-11-08 19:44 UTC, KyleAure commented
Here is the work I've been able to get done so far.
The `everything-jakarta-app` is currently failing with: 

```txt
java.lang.NoClassDefFoundError: javax/ws/rs/core/MultivaluedMap
	at org.microshed.testing.jaxrs.RestClientBuilder.build(RestClientBuilder.java:145)
	at org.microshed.testing.jupiter.MicroShedTestExtension.injectRestClients(MicroShedTestExtension.java:115)
	at org.microshed.testing.jupiter.MicroShedTestExtension.postConfigure(MicroShedTestExtension.java:76)
	at org.microshed.testing.jupiter.MicroShedTestExtension.beforeAll(MicroShedTestExtension.java:71)
	at org.microshed.testing.jupiter.MicroShedTestExtension.beforeAll(MicroShedTestExtension.java:58)
```

I transformed the core archive to use the Jakarta namespace but I believe there is still some dependency that is using javax packages. 
The line where this failure is happening is here: 
https://github.com/MicroShed/microshed-testing/blob/59daa359cf83ced24cee015c0b7931fcf2447bf2/core/src/main/java/org/microshed/testing/jaxrs/RestClientBuilder.java#L145

Which seems to suggestion that cxf is using javax packages, but when I check the dependency tree I see: 

```txt
|    +--- org.apache.cxf:cxf-rt-rs-client:3.4.1
|    |    +--- org.apache.cxf:cxf-rt-transports-http:3.4.1
|    |    |    \--- org.apache.cxf:cxf-core:3.4.1
|    |    |         +--- org.glassfish.jaxb:jaxb-runtime:2.3.3
|    |    |         |    +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.3
|    |    |         |    |    \--- jakarta.activation:jakarta.activation-api:1.2.2
|    |    |         |    +--- org.glassfish.jaxb:txw2:2.3.3
|    |    |         |    +--- com.sun.istack:istack-commons-runtime:3.0.11
|    |    |         |    \--- com.sun.activation:jakarta.activation:1.2.2
|    |    |         +--- com.fasterxml.woodstox:woodstox-core:6.2.1
|    |    |         |    \--- org.codehaus.woodstox:stax2-api:4.2.1
|    |    |         +--- org.apache.ws.xmlschema:xmlschema-core:2.2.5
|    |    |         \--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.3 (*)
|    |    +--- org.apache.cxf:cxf-core:3.4.1 (*)
|    |    \--- org.apache.cxf:cxf-rt-frontend-jaxrs:3.4.1
|    |         +--- org.apache.cxf:cxf-core:3.4.1 (*)
|    |         +--- jakarta.ws.rs:jakarta.ws.rs-api:2.1.6 -> 3.0.0
|    |         +--- jakarta.annotation:jakarta.annotation-api:1.3.5 -> 2.0.0
|    |         +--- org.apache.cxf:cxf-rt-transports-http:3.4.1 (*)
|    |         \--- org.apache.cxf:cxf-rt-security:3.4.1
|    |              \--- org.apache.cxf:cxf-core:3.4.1 (*)
```

<details>
  <summary>full ouput</summary>
```txt
------------------------------------------------------------
Project :microshed-testing-everything-jakarta-app
------------------------------------------------------------

annotationProcessor - Annotation processors and their dependencies for source set 'main'.
No dependencies

apiElements - API elements for main. (n)
No dependencies

archives - Configuration for archive artifacts.
No dependencies

compileClasspath - Compile classpath for source set 'main'.
+--- org.mongodb:mongo-java-driver:3.11.2
+--- jakarta.platform:jakarta.jakartaee-api:9.0.0
\--- org.eclipse.microprofile:microprofile:5.0
     +--- jakarta.enterprise:jakarta.enterprise.cdi-api:3.0.0
     |    +--- jakarta.interceptor:jakarta.interceptor-api:2.0.0
     |    |    \--- jakarta.annotation:jakarta.annotation-api:2.0.0
     |    \--- jakarta.inject:jakarta.inject-api:2.0.0
     +--- jakarta.ws.rs:jakarta.ws.rs-api:3.0.0
     +--- jakarta.json.bind:jakarta.json.bind-api:2.0.0
     +--- jakarta.json:jakarta.json-api:2.0.1
     +--- jakarta.annotation:jakarta.annotation-api:2.0.0
     +--- org.eclipse.microprofile.config:microprofile-config-api:3.0
     +--- org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api:4.0
     +--- org.eclipse.microprofile.health:microprofile-health-api:4.0
     +--- org.eclipse.microprofile.metrics:microprofile-metrics-api:4.0
     +--- org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:2.0
     +--- org.eclipse.microprofile.openapi:microprofile-openapi-api:3.0
     +--- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:3.0
     \--- org.eclipse.microprofile.opentracing:microprofile-opentracing-api:3.0

compileOnly - Compile only dependencies for source set 'main'. (n)
No dependencies

default - Configuration for default artifacts.
+--- org.mongodb:mongo-java-driver:3.11.2
+--- jakarta.platform:jakarta.jakartaee-api:9.0.0
\--- org.eclipse.microprofile:microprofile:5.0
     +--- jakarta.enterprise:jakarta.enterprise.cdi-api:3.0.0
     |    +--- jakarta.interceptor:jakarta.interceptor-api:2.0.0
     |    |    \--- jakarta.annotation:jakarta.annotation-api:2.0.0
     |    \--- jakarta.inject:jakarta.inject-api:2.0.0
     +--- jakarta.ws.rs:jakarta.ws.rs-api:3.0.0
     +--- jakarta.json.bind:jakarta.json.bind-api:2.0.0
     +--- jakarta.json:jakarta.json-api:2.0.1
     +--- jakarta.annotation:jakarta.annotation-api:2.0.0
     +--- org.eclipse.microprofile.config:microprofile-config-api:3.0
     +--- org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api:4.0
     +--- org.eclipse.microprofile.health:microprofile-health-api:4.0
     +--- org.eclipse.microprofile.metrics:microprofile-metrics-api:4.0
     +--- org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:2.0
     +--- org.eclipse.microprofile.openapi:microprofile-openapi-api:3.0
     +--- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:3.0
     \--- org.eclipse.microprofile.opentracing:microprofile-opentracing-api:3.0

implementation - Implementation only dependencies for source set 'main'. (n)
No dependencies

providedCompile - Additional compile classpath for libraries that should not be part of the WAR archive.
+--- jakarta.platform:jakarta.jakartaee-api:9.0.0
\--- org.eclipse.microprofile:microprofile:5.0
     +--- jakarta.enterprise:jakarta.enterprise.cdi-api:3.0.0
     |    +--- jakarta.interceptor:jakarta.interceptor-api:2.0.0
     |    |    \--- jakarta.annotation:jakarta.annotation-api:2.0.0
     |    \--- jakarta.inject:jakarta.inject-api:2.0.0
     +--- jakarta.ws.rs:jakarta.ws.rs-api:3.0.0
     +--- jakarta.json.bind:jakarta.json.bind-api:2.0.0
     +--- jakarta.json:jakarta.json-api:2.0.1
     +--- jakarta.annotation:jakarta.annotation-api:2.0.0
     +--- org.eclipse.microprofile.config:microprofile-config-api:3.0
     +--- org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api:4.0
     +--- org.eclipse.microprofile.health:microprofile-health-api:4.0
     +--- org.eclipse.microprofile.metrics:microprofile-metrics-api:4.0
     +--- org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:2.0
     +--- org.eclipse.microprofile.openapi:microprofile-openapi-api:3.0
     +--- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:3.0
     \--- org.eclipse.microprofile.opentracing:microprofile-opentracing-api:3.0

providedRuntime - Additional runtime classpath for libraries that should not be part of the WAR archive.
+--- jakarta.platform:jakarta.jakartaee-api:9.0.0
\--- org.eclipse.microprofile:microprofile:5.0
     +--- jakarta.enterprise:jakarta.enterprise.cdi-api:3.0.0
     |    +--- jakarta.interceptor:jakarta.interceptor-api:2.0.0
     |    |    \--- jakarta.annotation:jakarta.annotation-api:2.0.0
     |    \--- jakarta.inject:jakarta.inject-api:2.0.0
     +--- jakarta.ws.rs:jakarta.ws.rs-api:3.0.0
     +--- jakarta.json.bind:jakarta.json.bind-api:2.0.0
     +--- jakarta.json:jakarta.json-api:2.0.1
     +--- jakarta.annotation:jakarta.annotation-api:2.0.0
     +--- org.eclipse.microprofile.config:microprofile-config-api:3.0
     +--- org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api:4.0
     +--- org.eclipse.microprofile.health:microprofile-health-api:4.0
     +--- org.eclipse.microprofile.metrics:microprofile-metrics-api:4.0
     +--- org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:2.0
     +--- org.eclipse.microprofile.openapi:microprofile-openapi-api [...]

2023-11-08 21:31 UTC, appiepollo14 commented
@KyleAure I've updatet these; 'org.apache.cxf:cxf-rt-rs-client:3.6.2' 'org.apache.cxf:cxf-rt-rs-extension-providers:3.6.2' in the jakarta package. Then the test run but fails on restassured. RA needs updating as well but still relies partly on javax so an older implementation should be provided as well. IMO the jakarta transformer is not preffered and hopefully we can just rely on jakarta EE only.

2023-11-09 10:45 UTC, appiepollo14 commented
@KyleAure opened https://github.com/MicroShed/microshed-testing/pull/313 for what I've done so far. Hopefully the solution lies in the middle.

2023-11-09 17:41 UTC, KyleAure commented
@appiepollo14 looks like with a few more changes Jakarta tests are working!

2023-11-09 19:16 UTC, appiepollo14 commented
@KyleAure looks green to me?! 🚀

2023-11-09 19:23 UTC, KyleAure commented
@appiepollo14 wanna give this PR a review and if you approve I'll merge.

2023-11-09 20:42 UTC, appiepollo14 requested changes
Please use @ignore instead of commenting out this test. The rest is gr8.

2023-11-09 20:42 UTC, appiepollo14 commented on sample-apps/everything-jakarta-app/src/test/java/org/example/app/RestAssuredIT.java
> +    //@Test
Please use @ignore instead of commenting out this test.

2023-11-09 20:42 UTC, appiepollo14 commented on sample-apps/everything-jakarta-app/src/test/java/org/example/app/RestAssuredIT.java
> +    //@Test
Please use @ignore instead of commenting out this test.

2023-11-09 20:42 UTC, appiepollo14 commented on sample-apps/everything-jakarta-app/src/test/java/org/example/app/RestAssuredIT.java
> +    //@Test
Please use @ignore instead of commenting out this test.

2023-11-09 20:55 UTC, appiepollo14 approved these changes

2023-11-09 21:11 UTC, merged